---
apiVersion: v1
kind: Service
metadata:
  name: emoji-ui
  labels:
    app: emoji-ui
  namespace: app-test
spec:
  selector:
    app: emoji-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginx-port
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emoji-ui
  name: emoji-ui
  namespace: app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: emoji-ui
      name: web
    spec:
      containers:
        - name: emoji-ui
          image: satangops/react-emoji-demo:2
          ports:
            - name: nginx-port
              containerPort: 80
          resources: {}
      terminationGracePeriodSeconds: 30


